PR: Port the new quickstart
akka/akka-http-quickstart-java.g8 pull request #9
Opened 2017-09-03 06:04 UTC by agolubev

Ref #7 
it's migrated from scala version.
Docs still need to be updated. However, would like to do this as separate CR.

2017-09-04 12:35 UTC, raboof requested changes
Mostly looks good, one mistake. I noticed you removed the `pom.xml` and `build.gradle`, it might be good to bring those back for the Java example or is there a reason that complicates this?

2017-09-04 12:35 UTC, raboof commented on src/main/g8/src/main/java/com/lightbend/akka/http/sample/UserRegistryActor.java
> +import static jdk.nashorn.internal.runtime.regexp.joni.Config.log;
This probably wasn't intentional? :)

2017-09-11 02:27 UTC, agolubev commented on src/main/g8/src/main/java/com/lightbend/akka/http/sample/UserRegistryActor.java
> +import static jdk.nashorn.internal.runtime.regexp.joni.Config.log;
it makes sense - let me fix this

2017-09-11 04:04 UTC, agolubev commented
Ok, pushed requested changes

2017-09-18 10:14 UTC, raboof requested changes
Good improvements, noticed a number of issues still though :+1:!

2017-09-18 10:14 UTC, raboof commented on docs/src/main/paradox/json.md
> +//TBD
Looks like this is still left to be done

2017-09-18 10:14 UTC, raboof commented on docs/src/main/paradox/json.md
> +    While we used Spray JSON in this example, various other libraries are supported via the [Akka HTTP JSON](https://github.com/hseeberger/akka-http-json)
Since this note is indented, it is presented as a code block. Let's remove the indentation to make it look like a normal note and to fix the links.

2017-09-18 10:14 UTC, raboof commented on docs/src/main/paradox/json.md
> +    While we used Spray JSON in this example, various other libraries are supported via the [Akka HTTP JSON](https://github.com/hseeberger/akka-http-json)
(fixed this for the scala version in https://github.com/akka/akka-http-quickstart-scala.g8/pull/26)

2017-09-18 10:14 UTC, raboof commented on docs/src/main/paradox/json.md
> +Now that we've examined the example app thoroughly, let's test a few the remaining use cases.
'a few remaining use cases'

2017-09-18 10:14 UTC, raboof commented on docs/src/main/paradox/testing-routes.md
> +trait. Back there we said that we're doing this to eparate the infrastructure code (setting up the actor system and
It looks like the text of this page has not been updated yet

2017-09-18 10:14 UTC, raboof commented on src/main/g8/pom.xml
> +                    <mainClass>com.lightbend.akka.http.sample.QuickstartServer</mainClass>
nice

2017-09-18 13:25 UTC, agolubev commented
@raboof 
Yes, docs haven't been  revised  (in the description I mentioned this "Docs still need to be updated. However, would like to do this as separate CR.")
But let me look through them as part of this PR to have everything in one place.

Also: are you going to do/done any significant changes in scala peer project during last week I need to insert into java version?

2017-09-18 16:42 UTC, raboof commented
@agolubev Ah right didn't think of that - would be nice to have everything in one place! We merged a couple of small things into the scala peer project, but nothing significant (mostly version updates etc), and don't have anything in particular planned for the near future.

2017-09-29 01:12 UTC, ktoso commented
Would be cool to get this one merged btw.. :)

2017-09-29 01:52 UTC, agolubev commented
@ktoso  what are expectations from me? finished documenation?

2017-09-29 01:54 UTC, ktoso reviewed
Yes, it seems there's a few spots left to finish ("TBD"), otherwise looks good to go :)

2017-09-29 02:16 UTC, agolubev commented
Ok, will commit tomorrow.

2017-09-29 20:05 UTC, agolubev commented
@ktoso  I just pushed the rest of changes for documentation

2017-10-09 14:23 UTC, raboof reviewed
Couple of tiny comments but almost there! Thanks for all your efforts!

2017-10-09 14:23 UTC, raboof commented on docs/src/main/paradox/backend-actor.md
> +@@snip [UserRegistryActor.scala]($g8src$/java/com/lightbend/akka/http/sample/UserRegistryActor.java)
use the `UserRegistryActor.java` filename (though I believe we currently don't show it so it's no big deal)

2017-10-09 14:23 UTC, raboof commented on docs/src/main/paradox/backend-actor.md
> +or other [location-transparent](http://doc.akka.io/docs/akka/current/scala/general/remoting.html) techniques.
Might be good to link to the Java version of the documentation (here and e.g. at the bottom of this page)

2017-10-09 15:19 UTC, agolubev commented
@raboof  changes are pushed. Please let me know if I need to squash commits.

2017-10-24 15:46 UTC, raboof approved these changes
LGTM!

2017-10-25 00:43 UTC, ktoso commented
LGTM, thanks!

2017-10-25 00:44 UTC, merged

2017-10-25 01:29 UTC, agolubev commented
Yeah! Thanks

2017-10-25 01:33 UTC, ktoso commented
It should eventually show up on http://developer.lightbend.com/guides/ though it's always a bit confusing to get that done. We'll work on that on our end

2017-10-30 12:41 UTC, raboof commented
It's there! Thanks again :)